version: '3.2'

services:
  checkout:
    build: vcb
    ports:
      - "8101:80"
    restart: unless-stopped
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app
      - /data/cert/:/etc/apache2/ssl/
      - /data/logs/:/var/log/apache2/
    container_name: vietcombank-checkout
