<?php

namespace checkout\controllers;

use common\components\libs\Tables;
use common\models\db\CheckoutOrder;
use common\models\db\PaymentMethod;
use Yii;
use yii\web\Controller;

class HandleOrderBcaController extends Controller
{
    public function beforeAction($action)
    {
        Yii::$app->setTimeZone('UTC');


        if (in_array(get_client_ip(), ["::1", "183.91.7.129",
            "14.177.239.192",
            "101.99.7.132",
            "101.99.7.213",
            "14.177.239.244",
//            "183.91.4.105",
            "14.177.239.203"])) {
            return parent::beforeAction($action); // TODO: Change the autogenerated stub
        } else return false;

    }

    /** http://localhost/vietcombank-checkout/vcb/web/checkout/handle-order-bca/main?order_code= */


    public function actionMain($order_code)
    {
        $this->layout = 'blank';
        if (!empty($order_code)) {
//            $order_code = $_GET['order_code'];
            $checkoutOrder = CheckoutOrder::findOne(['order_code' => $order_code,'status' => CheckoutOrder::STATUS_PAID]);
            if ($checkoutOrder != null) {
                $buyer_name = $checkoutOrder->buyer_fullname;
                $buyer_email = $checkoutOrder->buyer_email;
                $title_mail = "Payment Confirmation E-Visa for register code " . $order_code;
                $currency = !is_null($checkoutOrder->currency) ? $checkoutOrder->currency : '';
                $amount = number_format($checkoutOrder->cashin_amount) . ' ' . $currency;

                $card_number = '';$payment_method_code = '';
                $payment_method_name = '';
                if (intval($checkoutOrder->transaction_id) != 0) {
                    $transaction_info = Tables::selectOneDataTable("transaction",
                        ["id = :id AND checkout_order_id = :checkout_order_id ", "id" => $checkoutOrder->transaction_id, "checkout_order_id" => $checkoutOrder->id]);
//

                    if ($transaction_info != false) {
                        $card_number = $transaction_info['card_info'] != null ? json_decode($transaction_info['card_info'])->card_number : '';

                        if(intval($transaction_info['payment_method_id']) != 0){
                            $payment_method = PaymentMethod::findOne($transaction_info['payment_method_id']);
                            if($payment_method!= null){
                                $payment_method_code = $payment_method->code!=null ? $payment_method->code : '';
                                if($payment_method_code == 'VISA-CREDIT-CARD'){
                                    $payment_method_name = 'PAY BY VISA';
                                }else if($payment_method_code == 'MASTERCARD-CREDIT-CARD'){
                                    $payment_method_name = 'PAY BY MASTERCARD';
                                }else if($payment_method_code == 'AMEX-CREDIT-CARD'){
                                    $payment_method_name = 'PAY BY AMEX';
                                }else{
                                    $payment_method_name = $payment_method_code; // phục vụ ktra lỗi
                                }
                            }
                        }
                    }


                }

                $time_paid = '';
                $time_send = '';
                if ($checkoutOrder->time_paid != null) {
                    $time_paid = date('H:i d/m/Y', $checkoutOrder->time_paid + 25200); // cộng thêm 7 múi giờ
                    $time_send = date('M d, h:i A', $checkoutOrder->time_paid + 25200);
                } else if ($checkoutOrder->time_created != null) {
                    $time_paid = date('H:i d/m/Y', $checkoutOrder->time_created + 25200);
                    $time_send = date('M d, h:i A', $checkoutOrder->time_created + 25200);
                }




//                var_dump($time_paid);
//                var_dump($amount);die();
                return $this->render('done', array(
                    'order_code' => $order_code,
                    'buyer_name' => $buyer_name,
                    'buyer_email' => $buyer_email,
                    'title_mail' => $title_mail,
                    'payment_method_name' => $payment_method_name,
                    'amount' => $amount,
                    'card_number' => $card_number,
                    'time_paid' => $time_paid,
                    'time_send' => $time_send,
                ));
            }
        }

//        var_dump('order_code: '.$order_code);
//        var_dump('buyer_name: '.$buyer_name);
//        var_dump('buyer_email: '.$buyer_email);
//        var_dump('title_mail: '.$title_mail);
//        var_dump('amount: '.$amount);
//        var_dump('card_number: '.$card_number);
//        var_dump('time_paid: '.$time_paid);
//        var_dump('time_send: '.date('M d, h:i A', strtotime($time_paid)));

        return $this->render('done');

    }
    public function actionMain1($order_code,$merchant_id)
    {
        $this->layout = 'blank';
        if (!empty($order_code)) {
//            $order_code = $_GET['order_code'];
            $checkoutOrder = CheckoutOrder::findOne(['order_code' => $order_code,'merchant_id' => $merchant_id]);
            if ($checkoutOrder != null) {
                $buyer_name = $checkoutOrder->buyer_fullname;
                $buyer_email = $checkoutOrder->buyer_email;
                $title_mail = "Payment Confirmation E-Visa for register code " . $order_code;
                $currency = !is_null($checkoutOrder->currency) ? $checkoutOrder->currency : '';
                $amount = number_format($checkoutOrder->cashin_amount) . ' ' . $currency;
                $description = $checkoutOrder->order_description;

                $card_number = '';$payment_method_code = '';
                $payment_method_name = '';
                if (intval($checkoutOrder->transaction_id) != 0) {
                    $transaction_info = Tables::selectOneDataTable("transaction",
                        ["id = :id AND checkout_order_id = :checkout_order_id ", "id" => $checkoutOrder->transaction_id, "checkout_order_id" => $checkoutOrder->id]);
//

                    if ($transaction_info != false) {
                        $card_number = $transaction_info['card_info'] != null ? json_decode($transaction_info['card_info'])->card_number : '';

                        if(intval($transaction_info['payment_method_id']) != 0){
                            $payment_method = PaymentMethod::findOne($transaction_info['payment_method_id']);
                            if($payment_method!= null){
                                $payment_method_code = $payment_method->code!=null ? $payment_method->code : '';
                                if($payment_method_code == 'VISA-CREDIT-CARD'){
                                    $payment_method_name = 'PAY BY VISA';
                                }else if($payment_method_code == 'MASTERCARD-CREDIT-CARD'){
                                    $payment_method_name = 'PAY BY MASTERCARD';
                                }else if($payment_method_code == 'AMEX-CREDIT-CARD'){
                                    $payment_method_name = 'PAY BY AMEX';
                                }else{
                                    $payment_method_name = $payment_method_code; // phục vụ ktra lỗi
                                }
                            }
                        }
                    }


                }

                $time_paid = '';
                $time_send = '';
                if ($checkoutOrder->time_paid != null) {
                    $time_paid = date('H:i d/m/Y', $checkoutOrder->time_paid + 25200); // cộng thêm 7 múi giờ
                    $time_send = date('M d, h:i A', $checkoutOrder->time_paid + 25200);
                } else if ($checkoutOrder->time_created != null) {
                    $time_paid = date('H:i d/m/Y', $checkoutOrder->time_created + 25200);
                    $time_send = date('M d, h:i A', $checkoutOrder->time_created + 25200);
                }




//                var_dump($time_paid);
//                var_dump($amount);die();
                return $this->render('done1', array(
                    'order_code' => $order_code,
                    'order_description' => $description,
                    'buyer_name' => $buyer_name,
                    'buyer_email' => $buyer_email,
                    'title_mail' => $title_mail,
                    'payment_method_name' => $payment_method_name,
                    'amount' => $amount,
                    'card_number' => $card_number,
                    'time_paid' => $time_paid,
                    'time_send' => $time_send,
                ));
            }
        }

//        var_dump('order_code: '.$order_code);
//        var_dump('buyer_name: '.$buyer_name);
//        var_dump('buyer_email: '.$buyer_email);
//        var_dump('title_mail: '.$title_mail);
//        var_dump('amount: '.$amount);
//        var_dump('card_number: '.$card_number);
//        var_dump('time_paid: '.$time_paid);
//        var_dump('time_send: '.date('M d, h:i A', strtotime($time_paid)));

        return $this->render('done1');

    }


    /**
     *
     *
     *
     * document.getElementById("buyer_name").innerHTML = "KAYLEE MCKENZIE DAHLE"
     * document.getElementById("buyer_email").innerHTML = "sethdahle@gmail.com"
     * document.getElementById("title_mail").innerHTML = "Payment Confirmation E-Visa for register code E221026USA64955637202"
     * document.getElementById("order_code_1").innerHTML = "E221026USA64955637202"
     * document.getElementById("amount").innerHTML = "638,976" + "VND"
     * document.getElementById("card_number").innerHTML = "414720.XXXX.XXXX.5074"
     * document.getElementById("time_paid").innerHTML = "18:08 26/10/2022"
     * document.getElementById("time_send").innerHTML = "Oct 26, 18:08 PM"
     */

}